name: List merged Pull Request in the Release
on: workflow_dispatch

jobs:
  list-merged-pull-requests:
    name: Release management comment
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: tiwanari/list-merged-pull-requests@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
