name: Update PR description

on:
  pull_request:
    types: [synchronize]

jobs:
  update-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update PR Description
        uses: nefrob/pr-description@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          content: "<!-- PR description - START -->New content here<!-- PR description - END -->"
          regex: "<!-- PR description - START -->.*?<!-- PR description - END -->"
          regexFlags: ims
