name: Update Pull Request Description

on:
  push:
    branches:
      - stage

jobs:
  update-pull-request-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update PR Description
        uses: nefrob/pr-description@v1.1.1
        with:
          content: "<!-- PR description - START -->New content here<!-- PR description - END -->"
          regex: "<!-- PR description - START -->.*?<!-- PR description - END -->"
          regexFlags: ims
          token: ${{ secrets.GITHUB_TOKEN }}

